name = "FilterDDP"
uuid = "3fc7acb0-3ec8-433f-906a-2d1e86d217d2"
version = "0.6.0"

[deps]
Crayons = "a8cc5b0e-0ffa-5ad4-8c14-923d3ee1735f"
FastLapackInterface = "29a986be-02c6-4525-aec4-84b980013641"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"
